teuthology/orchestra/opsys.py
teuthology/task/install.py

OpenSUSE Leap support

---

teuthology/lock.py
teuthology/matrix.py
teuthology/openstack/setup-openstack.sh
teuthology/task/internal.py

This aspires to address https://bugzilla.suse.com/show_bug.cgi?id=1023257 and https://bugzilla.suse.com/show_bug.cgi?id=1023263
The fix for the latter bug is entirely written by Loic Dachary.

Adapt teuthology-openstack to latest state of the world

---

teuthology/task/buildpackages.py

tasks: import buildpackages.py from ceph/ceph master

---

teuthology/openstack/__init__.py
teuthology/openstack/openstack-opensuse-42.1-user-data.txt
teuthology/openstack/openstack-opensuse-42.2-user-data.txt
teuthology/openstack/setup-openstack.sh
teuthology/packaging.py

openstack: add Leap 42.2 cloud image URL and fixed user-data

---

teuthology/orchestra/remote.py

remote: refuse to run chcon on OpenStack VMs as well as VPS

---

teuthology/salt.py
teuthology/task/ceph_cm_salt.py

Still to do:
* figure out how to populate `run` property
* set `run` grain to the value of the `run` property (do this in `init_minions()`)
* document the class itself (including usage example)

salt: Implement ping_minions_{serial,parallel} methods

---

teuthology/run.py
teuthology/salt.py

Activation of this code in master was an oversight.

Disable ceph_cm_salt while we work on it

---

scripts/openstack.py
teuthology/openstack/__init__.py
teuthology/openstack/openstack-user-data.txt
teuthology/openstack/setup-openstack.sh
teuthology/task/buildpackages.py
teuthology/task/buildpackages/Makefile
teuthology/task/buildpackages/common.sh
teuthology/task/buildpackages/make-deb.sh
teuthology/task/buildpackages/make-rpm.sh

@dachary I'm not sure what you mean by "in case we're using a fixture"? Under what circumstances would this conditional `test -d src` be false?

buildpackages: conditionally fetch tags from ceph/ceph.git

---

teuthology/salt.py
teuthology/task/ceph_cm_salt.py

salt: stop ping when all minions have answered

---

teuthology/openstack/__init__.py

openstack: enable openSUSE Leap 42.2

---

teuthology/orchestra/opsys.py
teuthology/orchestra/remote.py
teuthology/orchestra/test/test_opsys.py

Fixes: http://tracker.ceph.com/issues/18141

platform.linux_distribution() is deprecated; stop using it

---

teuthology/orchestra/opsys.py

opsys.py: make from_os_release support SUSE

---

teuthology/openstack/__init__.py
teuthology/openstack/openstack-opensuse-42.2-user-data.txt
teuthology/task/buildpackages/opensuse-42.2-user-data.txt

openstack --teardown also remove keypair and security groups

---

teuthology/openstack/setup-openstack.sh

openstack: install, enable and start fail2ban on teuthology VM

---

teuthology/salt.py

reformat salt.py to conform with pep8 style

---

docs/openstack_backend.rst

Signed-off-by: Loic Dachary <loic@dachary.org>

openstack: doc: --ceph is mandatory

---

teuthology/orchestra/daemon.py

The former registers without starting; the latter does both (as before).
Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit 2bcf6fe1133042dfdfae12d2d299a9348467ab62)

orchestra/daemon: separate register_daemon from add_daemon

---

scripts/openstack.py
teuthology/openstack/__init__.py
teuthology/openstack/setup-openstack.sh
teuthology/task/buildpackages.py

openstack: allow setting of teuthology VM params from command line

---

teuthology/openstack/__init__.py
teuthology/openstack/setup-openstack.sh
teuthology/openstack/test/test_openstack.py
teuthology/provision/openstack.py
teuthology/task/buildpackages.py
teuthology/task/buildpackages/make-rpm.sh

Fixes: https://github.com/SUSE/teuthology/issues/75

openstack: prefer vps-ssd-* flavors in OVH

---

teuthology/openstack/__init__.py
teuthology/openstack/openstack-opensuse-42.3-user-data.txt
teuthology/task/buildpackages/opensuse-42.3-user-data.txt

openstack: Support Leap 42.3 and work around "openstack image list" OVH limitation

---

requirements.txt
setup.py
teuthology/openstack/__init__.py
teuthology/openstack/openstack.yaml

Fixes: https://github.com/SUSE/teuthology/issues/90

openstack: ensure non-interactivity of custom YAML upload ssh and fix several other bugs as well

---

teuthology/task/full_sequential_finally.py

Fixes: https://github.com/SUSE/teuthology/issues/80
Fixes: https://github.com/SUSE/teuthology/issues/97

task/full_sequential_finally: run commands on unwind/cleanup

---

requirements.txt
teuthology/misc.py
teuthology/openstack/__init__.py
teuthology/openstack/openstack-user-data.txt
teuthology/openstack/setup-openstack.sh
teuthology/provision/openstack.py
teuthology/task/buildpackages.py
teuthology/task/buildpackages/Makefile

Make it possible to run simultaneously two and more teuthology server setups in the same openstack region.

Add multi-user support for openstack

---

requirements.txt
teuthology/openstack/openstack-sle-15.0-user-data.txt
teuthology/orchestra/opsys.py
teuthology/task/buildpackages/sle-15.0-user-data.txt

Support SLE-15

---

teuthology/misc.py

This runs on the test node, which might not have Python 2.

misc.py: saner write_file() and sudo_write_file()

---

teuthology/openstack/openstack-opensuse-15.0-user-data.txt
teuthology/orchestra/opsys.py
teuthology/task/buildpackages/opensuse-15.0-user-data.txt

openstack: support openSUSE Leap 15.0

---

teuthology/misc.py
teuthology/openstack/openstack-opensuse-15.0-user-data.txt
teuthology/task/buildpackages/opensuse-15.0-user-data.txt

openstack: user-data: tweak packages on openSUSE Leap 15.0

---

teuthology/openstack/openstack-opensuse-15.0-user-data.txt
teuthology/task/buildpackages/make-rpm.sh
teuthology/task/buildpackages/opensuse-15.0-user-data.txt

Temporary measure to make it possible for DeepSea to deploy Ceph
in openSUSE Leap 15.0
References: https://github.com/SUSE/DeepSea/issues/979

openstack: user-data: add filesystems:ceph:mimic OBS repo

---

teuthology/openstack/openstack-sle-12.3-user-data.txt
teuthology/task/install/__init__.py
teuthology/task/install/rpm.py

Introduce an "install_packages" configuration parameter controlling
whether packages are installed. Addition of repos is not affected.

install: skip package install phase, configurably

---

teuthology/task/install/rpm.py

Workaround for https://bugzilla.suse.com/show_bug.cgi?id=1089504
Anyway, whatever `install.py` does in the unwind phase is irrelevant because the machines will be destroyed (OpenStack) or reimaged (baremetal - FOG) anyway.

install: do not remove packages or clean zypper cache

---

teuthology/openstack/__init__.py
teuthology/openstack/setup-openstack.sh

Run teuthology on suse cloud7
- Add new flavors to use both for server and target
- Make use of network from config during cluster setup
- Fix floating IP creation
- Get rid of user-data template

Add ECP support

---

teuthology/suite/build_matrix.py
teuthology/suite/test/test_build_matrix.py
teuthology/task/install/rpm.py

backport https://github.com/ceph/teuthology/pull/1185

backport "build_matrix: ignore hidden files from upstream" and patch install task to always install ceph-test on all nodes

---

teuthology/salt.py

salt: extend ping timeout

---

teuthology/run.py
teuthology/salt.py

but be careful not to break non-SUSE test runs.

SUSE: Do not run ceph_cm_salt anymore

---

teuthology/task/install/__init__.py
teuthology/task/install/deb.py
teuthology/task/install/rpm.py
teuthology/test/task/test_install.py

Backport of:
* https://github.com/ceph/teuthology/pull/1192
* https://github.com/ceph/teuthology/pull/1202

[backport] install: make extra_packages distro-agnostic (in a limited way) and support extra_system_packages option

---

teuthology/openstack/openstack-teuthology.init

(cherry picked from commit b2ded04dae18ea6b8d7b73a659627d638818a55c)

openstack: add status_process function

---

teuthology/openstack/__init__.py

Fixes: https://github.com/SUSE/teuthology/issues/159

openstack: fail immediately if VM creation fails

---

teuthology/task/install/rpm.py

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1117201

 task/install: if extra_system_packages, install them all at once 

---

teuthology/openstack/openstack-sle-15.1-user-data.txt
teuthology/orchestra/opsys.py
teuthology/task/install/__init__.py
teuthology/task/install/rpm.py

install/rpm: add repos_only key for debugging issues with repos

---

teuthology/openstack/__init__.py
teuthology/openstack/bootstrap-teuthology.sh

Add support for github pr merge branches, like 'origin/pr/*/merge',
so it can be used to setup teuthology server using teuthology-openstack
command line tool with --teuthology-branch argument.

openstack: Support GitHub PR merge branches

---

teuthology/openstack/openstack-opensuse-15.1-user-data.txt
teuthology/orchestra/opsys.py

openstack: enable testing on openSUSE Leap 15.1

---

teuthology/test/test_repo_utils.py

Signed-off-by: Kyr <kyrylo.shatskyy@suse.com>

test: fix TestRepoUtils shared directory creation

---

teuthology/test/test_repo_utils.py

In this PR the older patch is reverted in favor of the one from the upstream.

Fix test repo utils

---

teuthology/nuke/__init__.py

Revert older commit in favor one from upstream

Fix all volumes nuke

---

bootstrap
tox.ini

bootstrap: fixes for recent teuthologies on recent openSUSEs

---

scripts/openstack.py
teuthology/openstack/__init__.py

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

teuthology-openstack: support test repo read from file
