SUSE/teuthology

teuthology/task/buildpackages/Makefile
teuthology/task/buildpackages/centos-6.5-user-data.txt
teuthology/task/buildpackages/centos-7.0-user-data.txt
teuthology/task/buildpackages/centos-7.1-user-data.txt
teuthology/task/buildpackages/centos-7.2-user-data.txt
teuthology/task/buildpackages/common.sh
teuthology/task/buildpackages/debian-8.0-user-data.txt
teuthology/task/buildpackages/make-deb.sh
teuthology/task/buildpackages/make-rpm.sh
teuthology/task/buildpackages/opensuse-42.1-user-data.txt
teuthology/task/buildpackages/sle-12.1-user-data.txt
teuthology/task/buildpackages/sle-12.2-user-data.txt
teuthology/task/buildpackages/ubuntu-12.04-user-data.txt
teuthology/task/buildpackages/ubuntu-14.04-user-data.txt
teuthology/task/buildpackages/ubuntu-16.04-user-data.txt
teuthology/task/buildpackages/user-data.txt

It is exactly the same in all branches. It really belongs in teuthology
and was placed in ceph-qa-suite because it required a more flexible
development cycle.
Signed-off-by: Loic Dachary <loic@dachary.org>

buildpackages: import from ceph/master

---

teuthology/openstack/setup-openstack.sh

Do not use shaman (it is the new default).
Signed-off-by: Loic Dachary <ldachary@redhat.com>

openstack: buildpackages is gitbuilder compatible

---

teuthology/openstack/setup-openstack.sh

In ubuntu 16.04
Signed-off-by: Loic Dachary <ldachary@redhat.com>

openstack: nginx root moved to /var/www/html

---

teuthology/openstack/setup-openstack.sh

It is a security issue that should be addressed when running long lived
clusters. But teuthology-openstack is meant to not last more than a few
days.
Signed-off-by: Loic Dachary <ldachary@redhat.com>

dnsmasq must respond to all requests

---

teuthology/openstack/__init__.py
teuthology/openstack/setup-openstack.sh
teuthology/task/buildpackages/make-rpm.sh

When this value is set, it is necessary to explicitly give --suite-repo and
--suite-branch. We would rather have the defaults for these come from
--ceph-repo and --ceph.

setup: do not set ceph_qa_suite_git_url in ~/.teuthology.yaml

---

teuthology/packaging.py

When a job completes, all Ceph packages installed are removed and then the repo is removed as well. Repo removal fails with:
```
2017-02-11 00:16:24,212.212 INFO:teuthology.orchestra.run.target213032075158:Running: 'sudo yum -y erase ceph-release'
2017-02-11 00:16:24,268.268 INFO:teuthology.orchestra.run.target213032075158.stderr:sudo: yum: command not found
```

packaging: SUSEify GitbuilderProject._remove_rpm_repo()

---

teuthology/nuke/actions.py
teuthology/openstack/openstack-opensuse-42.1-user-data.txt
teuthology/openstack/openstack-sle-12.2-user-data.txt
teuthology/run.py
teuthology/task/clock.py

Newer versions of ntpd have ntpdc support turned off by default,
to avoid NTP reflection/amplification.
See, e.g., https://mail-index.netbsd.org/netbsd-users/2015/08/04/msg016612.html

clock: use ntpq instead of ntpdc

---

teuthology/openstack/openstack-centos-6.5-user-data.txt
teuthology/openstack/openstack-centos-7.0-user-data.txt
teuthology/openstack/openstack-centos-7.1-user-data.txt
teuthology/openstack/openstack-centos-7.2-user-data.txt
teuthology/openstack/openstack-debian-8.0-user-data.txt
teuthology/openstack/openstack-opensuse-42.1-user-data.txt
teuthology/openstack/openstack-sle-12.2-user-data.txt
teuthology/openstack/openstack-ubuntu-12.04-user-data.txt
teuthology/openstack/openstack-ubuntu-14.04-user-data.txt
teuthology/openstack/openstack-ubuntu-16.04-user-data.txt
teuthology/openstack/openstack-user-data.txt
teuthology/task/buildpackages.py

With this tweak, Ubuntu 16.04 VMs come up with
```
ubuntu@target137074030173:~$ cat /etc/resolv.conf
domain teuthology
search teuthology
nameserver 137.74.29.118
nameserver 213.186.33.99
```
Do you know how to prevent the second nameserver line from being added?

user-data: tweak Ubuntu 16.04 user-data

---

teuthology/task/buildpackages/make-rpm.sh

make-rpm.sh breaks for kraken when run on SLE-12-SP2:
```
+ rpmbuild -ba --define '_unpackaged_files_terminate_build 0' --define '_topdir /tmp/release/sles/WORKDIR' ceph.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.F2hJfx
+ umask 022
+ cd /tmp/release/sles/WORKDIR/BUILD
+ cd /tmp/release/sles/WORKDIR/BUILD
+ rm -rf ceph-11.1.0
+ /usr/bin/bzip2 -dc /tmp/release/sles/WORKDIR/SOURCES/ceph-11.1.0-7423-g8f37fcc.tar.bz2
+ /bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd ceph-11.1.0
/var/tmp/rpm-tmp.F2hJfx: line 35: cd: ceph-11.1.0: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.F2hJfx (%prep)
```
EDIT: After pursuing a number of dead ends, I found the root cause. The buildpackages task uses `make-dist` to generate the tarball. In order for the tarball so generated …

buildpackages: fix make-rpm.sh for kraken + SUSE

---

teuthology/task/buildpackages/centos-7.3-user-data.txt

Tests are failing with:
2017-02-18T11:07:34.742 DEBUG:teuthology.misc:timeout 30m openstack server create --image 'teuthology-centos-7.3-x86_64'  --flavor hg-60-ssd --key-name teuthology --security-group teuthology --property ownedby=149.202.169.26 --user-data centos-7.3-user-data.txt --wait ceph-rpm-centos7-x86_64-basic-f65754e312f11823c5bb7e9fe24655f3fd68bcd2
2017-02-18T11:07:37.227 DEBUG:teuthology.misc:Can't open 'centos-7.3-user-data.txt': [Errno 2] No such file or directory: 'centos-7.3-user-data.txt'

buildpackages: add centos-7.3-user-data.txt

---

teuthology/openstack/test/test_openstack.py

```
>       assert 'Ubuntu 14.04' in l
E       assert 'Ubuntu 14.04' in '...
__init__.py                732 INFO     Distributor ID: Ubuntu
__init__.py                732 INFO     Description:    Ubuntu 16.04.1 LTS
__init__.py                732 INFO     Release:        16.04
__init__.py                732 INFO     Codename:       xenial
transport.py              1567 DEBUG    EOF in transport thread'
```
(This isn't exactly what the error message said, but close enough.)

tests: fix test_create

---

docs/openstack_backend.rst

Without sudo:
(virtualenv) ubuntu@teuthology:~$ pkill -f teuthology-worker
pkill: killing pid 6735 failed: Operation not permitted
pkill: killing pid 6736 failed: Operation not permitted
pkill: killing pid 6737 failed: Operation not permitted
pkill: killing pid 6738 failed: Operation not permitted
pkill: killing pid 6739 failed: Operation not permitted
pkill: killing pid 6740 failed: Operation not permitted
pkill: killing pid 6741 failed: Operation not permitted
pkill: killing pid 6742 failed: Operation not permitted
pkill: killing pid 6743 failed: Operation not permitted
pkill: killing pid 6744 failed: Operation not permitted
With sudo, it just works.

doc: add sudo to pkill and explain how to run a single test

---

teuthology/openstack/openstack-opensuse-42.1-user-data.txt
teuthology/openstack/openstack-sle-12.2-user-data.txt
teuthology/salt.py
teuthology/task/ceph_cm_salt.py

This enables salt to be used for initial target initialisation as well as target tests.

Refactor salt class to be reusable

---

scripts/openstack.py

This argument is no longer optional in teuthology-suite. This leads to
unexpected behaviour when teuthology-openstack is run with '-c master'.
The openstack parser swalloed this argument, since it assumed this was
the default values, leading to teuthology-suite bailing out.

teuthology-openstack: -c argument for ceph branch is no longer optional

---

teuthology/openstack/__init__.py
teuthology/provision/openstack.py

The Teuthology VM only needs to open for ssh, pulpito and paddles
traffic. The worker VMs should only communicate with each other and the
Teuthology VM.
Test instance here http://158.69.92.41:8081/

openstack: restrict traffic from world to bare minimum

---

teuthology/openstack/openstack-opensuse-42.1-user-data.txt

In 42.2 this conflicts with rsyslog. In 42.1 the package is not
installed and the remove operation does nothing.

openstack/userdata: remove package systemd-logger

---

teuthology/task/buildpackages/common.sh

Note: we are guaranteed to be in the local clone when `install_deps` (the function) is called, so `install-deps.sh` (the script) is "just there".

buildpackages: use install-deps.sh from local clone

---

teuthology/misc.py
teuthology/salt.py

The changes in teuthology/misc.py don't change existing calls, so doesn't change anything in existing code. These changes simply add some flexibility.
Th salt changes change the minion_id to hostnames and simplify some calls using misc.py.

salt: use hostname for minion_id; make some misc fcts more flexible

---

teuthology/openstack/__init__.py

If one security group (teuthology and teuthology-worker) is not present,
delete the existing group and recreate both.
Fixes: #62 

openstack setup: recreate security groups if one is missing

---

teuthology/provision/openstack.py

Attempted workaround for this issue:
```
2017-03-23T12:33:20.684 DEBUG:teuthology.misc::sh: openstack --quiet volume show  -f json target217182140122-1
2017-03-23T12:34:22.140 DEBUG:teuthology.misc:{
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"size": 10,
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"status": "available",
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"properties": "ownedby='217.182.143.170'",
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"user_id": "122b249e82994f5aa8ec6a31b7891df5",
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"description": null,
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"availability_zone": "nova",
2017-03-23T12:34:22.146 DEBUG:teuthology.misc:"bootable": "false",
2017-03-23T12:34:22.147 DEBUG:teuthology.misc:"encrypted": false, …
```

provision/openstack: put "add volume" in a retry loop

---

teuthology/openstack/__init__.py

Ansible has higher memory requirements these days. Keep the default
flavor to the minimum because it is used during tests.
Signed-off-by: Loic Dachary <loic@dachary.org>

openstack: increase teuthology flavors

---

teuthology/packaging.py

Otherwise the ceph packages from OBS are preferred because RPM evaluates, e.g.,
12.0.2+git.1493341348.9148e53 as a higher version number than
12.0.2-276.gf27d4b00ed.

packaging: add ceph-rpm-under-test zypper repo with high priority

---

teuthology/task/ansible.py

Newer ansibles start 5 parallel processes on every invocation of
ansible-playbook. This can easily overwhelm the teuthology VM.

task/ansible.py: tell ansible-playbook not to fork

---

teuthology/task/install/rpm.py

Since teuthology is used to automate CI testing, it is undesirable to
install anything more than is necessary to run the tests.
Fixes: #84

task: install: rpm: zypper install with --no-recommends

---

teuthology/salt.py

Fixes: https://github.com/SUSE/teuthology/issues/85

salt: ignore salt test.ping non-zero status code

---

requirements.txt
teuthology/salt.py

If several ceph-cm-salt jobs run at once, they race to restart the
salt-master.service on the teuthology VM, and unpleasantness ensues.
Fixes: https://github.com/SUSE/teuthology/issues/87

salt: implement locking mechanism around salt-master restart

---

teuthology/task/buildpackages/make-rpm.sh

Address error message "Source '...' does not contain the desired medium" when
repos get stale.

buildpackages: install createrepo package carefully

---

requirements.txt

The requests and cryptography modules got updated, giving rise
to several conflicts with ceph-workbench, which pins the versions
of its dependencies.

requirements.txt: pin version numbers of several modules

---

teuthology/salt.py

When several ceph_cm_salt tests are run in parallel, they were stepping on
eachother's toes and causing corruption of the Salt Master's database. The
immediate sign was failure of the "systemctl restart salt-master.service"
command on the teuthology VM. To address this, https://github.com/SUSE/teuthology/pull/88 was merged. However, 
that was not enough - the problem persisted. Hence this PR.

salt: more aggressive locking

---

teuthology/openstack/openstack-opensuse-42.2-user-data.txt
teuthology/openstack/openstack-opensuse-42.3-user-data.txt
teuthology/openstack/openstack-sle-12.2-user-data.txt

gcc is needed to run certain test scripts in qa/workunits/

openstack: install gcc on every SUSE test node

---

teuthology/packaging.py
teuthology/task/install/rpm.py

Also refresh zypper metadata cache immediately after adding new repo.
Later, when the install task starts to use real RPMs/repos (e.g. from OBS), I will need to add some logic to not pass `--no-gpg-checks` if using "real" repos.

Disable GPG checks in the install task

---

teuthology/openstack/openstack-sle-15.0-user-data.txt
teuthology/provision/openstack.py
teuthology/task/buildpackages/sle-15.0-user-data.txt

The image generation script is overriding the disable_root setting in
/etc/cloud/cloud.cfg. As a result, openstack seeds the key in
/root/.ssh/authorized_keys instead of /home/sles/.ssh/authorized_keys
The problem was, our user-data was copying /home/sles/.ssh/authorized_keys - 
as a result, teuthology could not SSH in.

Fix SLE15 user-data scripts

---

teuthology/task/buildpackages/make-rpm.sh

In buildpackages we don't care what versioning concept a given spec file is using - we just steamroll over it.

buildpackages: force version, release, tarball name

---

teuthology/orchestra/opsys.py

Treat 'opensuse-leap' as equivalent to 'opensuse'

Add new openSUSE Leap ID for os-release

---

teuthology/openstack/openstack-teuthology.init

This patch makes it possible to stop/start only teuthology workers and leave the rest of services alone.
Also it introduces new teuthology service commands to restart pulpito and paddles separately.
It mainly addresses the issues for fixing broken teuthology service when paddles becomes irresposible or some of the workers unexpectedly die.

Restart dead workers

---

docker/Dockerfile
docker/README.txt

Build:
`sudo docker build -t teuthology_leap .`
Use:
We can pass openrc.sh args as env-file after some modifications:
https://docs.docker.com/edge/engine/reference/commandline/run/#set-environment-variables--e---env---env-file
`sed 's/export //g' ../ovh-openrc.sh | tee ovh.list` # also remove `unset` vars
`docker run --env-file ../ovh.list  --rm -it teuthology_leap`
Execute your commands.
Signed-off-by: Shyukri Shyukriev <shshyukriev@suse.com>

Dockerfile v1 based on opensuse:42.3 and not using virtualenv.

---

teuthology/task/buildpackages/Makefile

The teuthology images no longer have the right repos for building Ceph.
Use the makecheck images instead.

buildpackages: use makecheck image to instantiate build VM

---

teuthology/openstack/openstack-user-data.txt
teuthology/openstack/setup-openstack.sh

When trying to deploy teuthology on openstack with several networks
and non unique subnet addresses setup-openstack script fails to add
nodes to paddles databases.
This patch removes duplicates while getting default_subnets.

Fix cannot populate paddles

---

scripts/openstack.py
scripts/suite.py
teuthology/config.py
teuthology/run_tasks.py
teuthology/suite/placeholder.py
teuthology/suite/run.py
teuthology/task/dump_ctx.py
teuthology/task/print.py
teuthology/task/sleep.py

With this option, all jobs in the run sleep for the given number of seconds as
the very last thing they do, regardless of success or failure.
Use case: interactive debugging

suite: Implement --sleep-before-teardown option

---

teuthology/openstack/__init__.py

(cherry picked from commit 1017722ab3044bbcc208f3e22369e583c61f4e92)

openstack: use ssh identity as key_filename by default

---

teuthology/openstack/__init__.py
teuthology/openstack/test/test_openstack.py

The form "ip floating" is deprecated: use "floating ip" instead.

openstack: use non-deprecated command form "floating ip"

---

teuthology/task/internal/__init__.py

Addresses error message:
AttributeError: 'tuple' object has no attribute 'split'

Fix fetch_binaries_for_coredumps

---

teuthology/openstack/setup-openstack.sh

Unfortunate typo instroduced in sha1 e491969d4b5b9dca710d1ce89f0cde918bbee1b4
which fixed ECP nodes creation and broke OVH nodes creation.

Fix ovh paddles populate

---

teuthology/task/install/rpm.py
teuthology/task/install/util.py

Fixes:
```
2018-10-11T10:16:53.414 INFO:teuthology.orchestra.run.target217182141091.stdout:Problem: ceph-test-12.2.8+git.1536505967.080f2248ff-2.17.2.x86_64 requires librbd.so.1()(64bit), but this requirement cannot be provided
2018-10-11T10:16:53.414 INFO:teuthology.orchestra.run.target217182141091.stdout:  uninstallable providers: librbd1-12.1.0+git.1498654198.20d6a47cc9-1.4.x86_64[base_repo5]
2018-10-11T10:16:53.414 INFO:teuthology.orchestra.run.target217182141091.stdout:                   librbd1-12.2.8+git.1536505967.080f2248ff-2.17.2.x86_64[ceph_repo5]
2018-10-11T10:16:53.414 INFO:teuthology.orchestra.run.target217182141091.stdout:                   librbd1-12.2.7+git.1531910353.c0ef85b854-2.12.1.x86_64[update_repo5]
2018-10-11T10:16:53.414 …
```

task/install: allow ceph-test to be installed with vendor change

---

teuthology/worker.py

The patch fixes uncaught exception RuntimeError:
I could not figure out the owner of the requested job.
Please pass --owner <owner>.
Worker dies with unhandled exception in run_with_watchdog
if it can't figure out owner of a job, which it tries
to kill when job runs longer then given limit of time.
(cherry picked from commit c623e60210e3d1ab9c300e16c756392b54a28e18)

Fix worker can't figure out owner of a job

---

teuthology/openstack/__init__.py
teuthology/task/install/rpm.py

Priority can be set adding optional '!' symbol with a number between
name and url. Internally there will be a 'priority' field added
next to 'name' and 'url' fields to the yaml definition.
Usage examples:
--test-repo 'first-repo:http://hostname.domain/no-priority/repo'
--test-repo 'second-repo!99:http://hostname.domain/default-priority/repo'
--test-repo 'third-repo!1:http://hostname.domain/highest-priority/repo'
--test-repo 'fourth-repo!2:http://hostname.domain/next-priority/repo'
--test-repo 'fifth-repo!0:http://hostname.domain/zero-priority/repo'
Notes for zypper:
The higher the number, the lower the priority.
No priority is equivalent to 99 or 0 priorities.

Add optional priority for --test-repo

---

scripts/openstack.py
teuthology/openstack/__init__.py

Add --nameserver option to teuthology-openstack cli tool so
teuthology cluster can be deployed and configured to use
customly provided dns

teuthology-openstack: add nameserver option

---

teuthology/openstack/__init__.py

When creating a teuthology openstack cluster and not
requesting any suite suite run the teuthology-openstack
quits silently not giving information where the cluster
is created and how its services can be reached.
This fix addresses the issue above.

teuthology-openstack: add banner after cluster creation

---

teuthology/openstack/__init__.py

After deployment teuthology cluster on openstack, teuthology
service status-paddles and status-pulpito commands report
'dead', however paddles and pulpito are running.
This fix addresses this issue.

openstack: fix pulpito and paddles status in init script

---

teuthology/suite/placeholder.py
teuthology/task/install/__init__.py
teuthology/task/install/rpm.py

It's safe to assume that downstream will not be running the ceph-deploy
task.

placeholder: drop ceph-deploy overrides yaml

---

teuthology/openstack/__init__.py

d6be711301fe7331acd428ab261ea648ef86305f broke the t-o deployment,
causing it to fail with the following Traceback:
2018-10-25 17:23:46,078.078 DEBUG:teuthology.misc:No server with a name
or ID of 'teuth-jschmid' exists.
Traceback (most recent call last):
File "/home/jxs/projects/teuthology/teuthology/v/bin/teuthology-openstack", line 11, in <module>
load_entry_point('teuthology', 'console_scripts', 'teuthology-openstack')()
File "/home/jxs/projects/teuthology/teuthology/scripts/openstack.py", line 7, in main
sys.exit(teuthology.openstack.main(parse_args(argv), argv))
File "/home/jxs/projects/teuthology/teuthology/teuthology/openstack/__init__.py", line 1310, in main
return TeuthologyOpenStack(ctx, teuth_config, argv).main()
File …

teuthology-openstack: fix broken deployment

---

scripts/openstack.py
teuthology/openstack/__init__.py

We do not want to deploy cluster by mistake, so it is
reasonable to have dedicated option for cluster deployment,
like --setup.

teuthology-openstack: do not deploy cluster by default

---

teuthology/openstack/__init__.py

Refactor teuthology-openstack so it gets openstack instance once.
Allow to run suite without prior setup() invocation.

openstack: add get_instance method

---

teuthology/openstack/__init__.py
teuthology/provision/openstack.py

Once in awhile, a created volume fails to become available within
a reasonable period of time. When this happens, the entire test job
fails with the following error:
2018-10-02T06:52:44.106 ERROR:teuthology.provision.openstack:'volume
target192168000058-2' reached maximum tries (100) after waiting for 200
seconds
With this commit, we catch that exception and retry with a new volume.

openstack: retry if volume create+attach operation fails

---

teuthology/orchestra/remote.py

Fix code to allow reconncting to a node after the connection was lost.
This patch introduces a 'context' parameter for
teuthology.orchestra.remote's run(..) method which
works around an issue with paramiko.
Signed-off-by: Joshua Schmid <jschmid@suse.de>

Draft implementation to survive reboots

---

teuthology/openstack/openstack-opensuse-15.0-user-data.txt

With these changes, it once again becomes possible to run jobs on openSUSE 15.0.

user-data: update openSUSE 15.0 user-data

---

teuthology/task/clock.py

"chronyc sources" likes to fail, for no good reason, on openSUSE 15.0:
```
2018-11-10T08:59:39.907 INFO:teuthology.orchestra.run.target192168000045:Running: 'sudo systemctl stop ntpd.service || sudo systemctl stop chronyd.service ; sudo ntpd -gq || sudo chronyc makestep ; sudo systemctl start ntpd.service || sudo systemctl start chronyd.service ; PATH=/usr/bin:/usr/sbin ntpq -p || PATH=/usr/bin:/usr/sbin chronyc sources'
2018-11-10T08:59:40.022 INFO:teuthology.orchestra.run.target192168000045.stderr:Failed to stop ntpd.service: Unit ntpd.service not loaded.
2018-11-10T08:59:40.124 INFO:teuthology.orchestra.run.target192168000045.stderr:sudo: ntpd: command not found
2018-11-10T08:59:40.172 INFO:teuthology.orchestra.run.target192168000045.stdout:506 Cannot talk to daemon …
```

teuthology/task/clock.py: do not fail

---

teuthology/run_tasks.py

It turns out it's possible for a file qa/tasks/foo.py to exist,
yet importing it still raises an ImportError because it references a
non-existent symbol.
In this case, teuthology was clobbering the real ImportError with its
own bogus text.
Fixes: http://tracker.ceph.com/issues/37370
(cherry picked from commit af7103eca2b7571697b7b239a24fe2898e949d56)

run_tasks.py: allow _import to raise the right ImportError

---

teuthology/config.py
teuthology/openstack/setup-openstack.sh

Fixes: https://trello.com/c/X5StTYxZ/378-teuthology-runs-in-ecp-use-needlessly-large-flavor
Related-to: https://github.com/SUSE/ceph/pull/253
---

config: use lower default RAM hint for openstack provisioning

---

teuthology/openstack/__init__.py

Hide OS_ variables in the log, so it can't be easily
read by human and steal secrets.

openstack: hide OS_ variables dumping

---

teuthology/orchestra/remote.py

This resolves the issue when remote lost connection
if the command was a reboot of the host and there was
only one unsuccessful try to reconnect and as a result
was loosing transport and got stuck with message like:
WARNING:tasks.deepsea.orch:No connection established yet..
Signed-off-by: Kyr <kyrylo.shatskyy@suse.com>

orchestra: fix no connection after reboot

---

teuthology/nuke/__init__.py

Do not allow teuthology-nuke to delete all volumes on openstack.
There is a bug on some openstack clients that --name option
does not work correctly for 'openstack volume list' in contrast
to 'openstack server list' and lists all available volumes
ignoring '--name' option at all.

openstack: fix all volumes nuke

---

scripts/openstack.py
scripts/suite.py
teuthology/suite/__init__.py

This patch introduces TEUTH_ based environment variables
which can be used to avoid bulky commands while overiding
default values for some of the teuthology arguments.
Removes mandatory of --ceph option for teuthology-suite,
and defaults to 'master'.
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
(cherry picked from commit f0db3fe73429599345a58485ae7e5f2c4d641a24)
Conflicts:
scripts/openstack.py
scripts/suite.py

openstack: take defaults from environment

---

teuthology/task/internal/syslog.py

When running the new iSCSI smoke test, tcmu-runner emits a syslog
message that was not whitelisted:
2019-03-27T10:00:17.292154+00:00 target192168000056 tcmu-runner[37366]: 2019-03-27 10:00:17.291 37366 [INFO] load_our_module:537: Inserted module 'target_core_user'
Since the message is at severity level INFO, it was causing teuthology
to raise a red flag.

syslog.py: whitelist innocent tcmu-runner log message

---

scripts/suite.py
teuthology/suite/__init__.py

By default suite branch must be equal to ceph one.
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
(cherry picked from commit 8c37d3b7ebc411282ff0c56df73675d7f1757a98)

teuthology-suite: no default value for suite branch

---

teuthology/task/internal/syslog.py

During iSCSI Gateway (igw) test runs, tcmu-runner sometimes emits syslog
messages at INFO level. According to the ceph-iscsi developers, these messages
are harmless and should not cause tests to fail.

syslog.py: whitelist INFO-level tcmu-runner syslog messages

---

teuthology/task/install/rpm.py

This reverts commit 9f8456c735d369f295ea4eca4eee12d74e495537.
(librados3 is dead, long live librados2)

Revert "install/rpm: librados3 in SES6+"

---

teuthology/openstack/__init__.py

We need to always pass the parameters below in order to make it work using
environment variables:
--ceph
--ceph-repo
--suite-repo
--suite-branch
--teuthology-branch
Signed-off-by: gkyratsas <gkyratsas@suse.com>

openstack: always pass branch and repo parameters

---

requirements.txt

"./bootstrap" on latest master fails with:
ERROR: paramiko 2.6.0 has requirement cryptography>=2.5, but you'll have
cryptography 2.2.1 which is incompatible.

requirements.txt: bump cryptography version to 2.7

---

teuthology/run.py

Companion PR to https://github.com/SUSE/ceph/pull/340
(for alignment with upstream)

run.py: automatically run the "clock" task

---

scripts/openstack.py
teuthology/openstack/__init__.py

Instead of appending possible private keyfile paths internally, make
that the default for the --key-filename command line argument so users
see it when looking at the help.
If --key-filename is given, only that key is used now (instead of
silently trying the default keys)
(cherry picked from commit c90e9d0768741fd0ac59ececa691534a34a22300)

openstack: Make used private keys explicit
